# Generated by Django 4.1.7 on 2023-11-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="lat",
            field=models.FloatField(default=0, verbose_name="Широта"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="lon",
            field=models.FloatField(default=0, verbose_name="Долгота"),
            preserve_default=False,
        ),
    ]
