# Generated by Django 4.1.7 on 2023-11-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, verbose_name="Дата")),
                ("temp", models.CharField(max_length=10, verbose_name="Температура")),
                ("humidity", models.CharField(max_length=10, verbose_name="Влажность")),
                ("notes", models.CharField(max_length=127, verbose_name="Заметки")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="geography.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ("date",),
            },
        ),
    ]
